server:
  port: 8080

spring:
  application:
    name: api-gateway

# ?: /order/** ??? order-service? ???

# Eureka ?? ???? ?? ???? uri? http://localhost:{??}? ?? ???? ?.
# 한글 UTF-8 적용되었는지 테스트 주석
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://localhost:8081
          predicates:
            - Path=/order/**
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/product/**
